<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NetArchTest.eNhancedEdition" Version="1.4.5" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Valitana.Api\Valitana.Api.csproj" />
    <ProjectReference Include="..\..\src\Valitana.Application\Valitana.Application.csproj" />
    <ProjectReference Include="..\..\src\Valitana.Contracts\Valitana.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Valitana.Domain\Valitana.Domain.csproj" />
    <ProjectReference Include="..\..\src\Valitana.Infrastructure\Valitana.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Valitana.Publisher\Valitana.Publisher.csproj" />
    <ProjectReference Include="..\..\src\Valitana.SignalR\Valitana.SignalR.csproj" />
  </ItemGroup>

</Project>
